#include "l_letter.h"
#include "src/util.h"

L_Text_Obj L_TEXTS_OBJS[L_TEXT_COUNT] = {
	{ "hold / for help",
	  40,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 4, WINDOW_HEIGHT - 50, -1, -1 } },

	{ "0-9 ",
	  80,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 80, 140, -1, -1 } },
	{ "shift",
	  80,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 80, 240, -1, -1 } },
	{ "ctrl",
	  80,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 80, 340, -1, -1 } },
	{ "E",
	  80,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 80, 440, -1, -1 } },
	{ "S",
	  80,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 80, 540, -1, -1 } },
	{ "W",
	  80,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 80, 640, -1, -1 } },
	{ "N",
	  80,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 80, 740, -1, -1 } },
	{ "C",
	  80,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 420, 140, -1, -1 } },
	{ "H",
	  80,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 420, 240, -1, -1 } },
	{ "G",
	  80,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 420, 340, -1, -1 } },
	{ "- arrow keys\n  navigate menu",
	  80,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_LEFT,
	  { 760, 125, -1, -1 } },
	{ "- space toggle pane",
	  80,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 760, 325, -1, -1 } },
	{ "- escape backtrack",
	  80,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 760, 425, -1, -1 } },
	{ "- enter continue",
	  80,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 760, 525, -1, -1 } },
	{ "- , clear state",
	  80,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 760, 625, -1, -1 } },

	{ "Hand",
	  50,
	  L_COLOR_GREEN,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 10, 130, -1, -1 } },
	{ "Hand",
	  50,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 10, 130, -1, -1 } },
	{ "Valid",
	  50,
	  L_COLOR_GREEN,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 200, 130, -1, -1 } },
	{ "Invalid",
	  50,
	  L_COLOR_YELLOW,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 200, 130, -1, -1 } },
	{ "Dora",
	  50,
	  L_COLOR_GREEN,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 10, 303, -1, -1 } },
	{ "Dora",
	  50,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 10, 303, -1, -1 } },

	{ "Seat wind",
	  50,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 10, 516, -1, -1 } },
	{ "Seat wind",
	  50,
	  L_COLOR_GREEN,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 10, 516, -1, -1 } },
	{ "Prevalent wind",
	  50,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 10, 729, -1, -1 } },
	{ "Prevalent wind",
	  50,
	  L_COLOR_GREEN,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 10, 729, -1, -1 } },

	{ "t tsumo",
	  70,
	  L_COLOR_RED,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 500, 330, -1, -1 } },
	{ "t tsumo",
	  70,
	  L_COLOR_GREEN,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 500, 330, -1, -1 } },
	{ "r riichi",
	  70,
	  L_COLOR_RED,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 500, 410, -1, -1 } },
	{ "r riichi",
	  70,
	  L_COLOR_GREEN,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 500, 410, -1, -1 } },
	{ "d double riichi",
	  70,
	  L_COLOR_RED,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 500, 490, -1, -1 } },
	{ "d double riichi",
	  70,
	  L_COLOR_GREEN,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 500, 490, -1, -1 } },
	{ "i ippatsu",
	  70,
	  L_COLOR_RED,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 500, 570, -1, -1 } },
	{ "i ippatsu",
	  70,
	  L_COLOR_GREEN,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 500, 570, -1, -1 } },
	{ "z haitei",
	  70,
	  L_COLOR_RED,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 500, 650, -1, -1 } },
	{ "z haitei",
	  70,
	  L_COLOR_GREEN,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 500, 650, -1, -1 } },
	{ "m chankan",
	  70,
	  L_COLOR_RED,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 500, 730, -1, -1 } },
	{ "m chankan",
	  70,
	  L_COLOR_GREEN,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 500, 730, -1, -1 } },
	{ "k rinshan kaihou",
	  70,
	  L_COLOR_RED,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 500, 810, -1, -1 } },
	{ "k rinshan kaihou",
	  70,
	  L_COLOR_GREEN,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 500, 810, -1, -1 } },
	{ "u tenhou",
	  70,
	  L_COLOR_RED,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 500, 890, -1, -1 } },
	{ "u tenhou",
	  70,
	  L_COLOR_GREEN,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 500, 890, -1, -1 } },

	{ "open",
	  100,
	  L_COLOR_GREEN,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { -1, -1, -1, -1 } },
	{ "closed",
	  100,
	  L_COLOR_YELLOW,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { -1, -1, -1, -1 } },

	{ "honba",
	  80,
	  L_COLOR_RED,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 10, 820, -1, -1 } },
	{ "honba",
	  80,
	  L_COLOR_GREEN,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 10, 820, -1, -1 } },
	{ "0",
	  100,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 300, 810, -1, -1 } },
	{ "^",
	  80,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 130, 780, -1, -1 } },
	{ "v",
	  50,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 130, 890, -1, -1 } },

	{ "ERROR!",
	  100,
	  L_COLOR_RED,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { -1, -1, -1, -1 } },
	{ "OK",
	  100,
	  L_COLOR_WHITE,
	  WINDOW_WIDTH / 5 * 4,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { -1, -1, -1, -1 } },

	{ "Yaku",
	  100,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { -1, -1, -1, -1 } },
	{ "Yakuman",
	  100,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { -1, -1, -1, -1 } },
	{ "Fu",
	  100,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { -1, -1, -1, -1 } },

	{ "Han - ",
	  50,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { -1, -1, -1, -1 } },
	{ "0",
	  50,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { -1, -1, -1, -1 } },
	{ "/Fu - ",
	  50,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { -1, -1, -1, -1 } },
	{ "0",
	  50,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { -1, -1, -1, -1 } },
	{ "Honba - ",
	  50,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { -1, -1, -1, -1 } },
	{ "0",
	  50,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { -1, -1, -1, -1 } },
	{ "Dora - ",
	  50,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { -1, -1, -1, -1 } },
	{ "0",
	  50,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { -1, -1, -1, -1 } },

	{ "Dealer ron",
	  80,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { -1, -1, -1, -1 } },
	{ "Dealer tsumo",
	  80,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { -1, -1, -1, -1 } },
	{ "Non Dealer ron",
	  80,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { -1, -1, -1, -1 } },
	{ "Non Dealer tsumo",
	  80,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { -1, -1, -1, -1 } },
	{ "0",
	  80,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { -1, -1, -1, -1 } },

	{ "DEBUG NOT UPDATED YET",
	  80,
	  L_COLOR_WHITE,
	  0,
	  TTF_HORIZONTAL_ALIGN_CENTER,
	  { 200, 200, -1, -1 } },
};
