name: Build and Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install build-essential ninja-build cargo clang-format \
            gnome-desktop-testing libasound2-dev libpulse-dev \
            libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
            libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
            libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
            libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libfreetype-dev \
            libpipewire-0.3-dev libwayland-dev
          pipx install meson --force

      - name: Install cbindgen via Cargo
        run: cargo install cbindgen

      - name: Install Linux-specific headers
        run: sudo apt-get install -y libudev-dev libasound2-dev

      - name: Run Check Command
        run: make format-check

      - name: Run build
        run: |
          rm -rf build
          make build
